version: "3.9"

services:
    testausserveri-id:
        build:
            context: .
            network: host
        restart: unless-stopped
        depends_on:
            - testausserveri-id-mongo
        env_file:
            - .env
        environment:
            - DATABASE_URL=mongodb://testausserveri-id-mongo:27017
        ports:
            - "7080:7080"
        links:
            - testausserveri-id-mongo
        stdin_open: true
        tty: true
    testausserveri-id-mongo:
        container_name: testausserveri-id-mongo
        restart: unless-stopped
        image: mongo
        volumes:
        - ./data:/data/db
