version: "3.9"

services:
    testausserveri-id-example:
        restart: unless-stopped
        env_file:
            - .env
        build:
            context: .
            network: host
        ports:
            - "7081:80"
